orbs:
  compare-url: iynere/compare-url@1.2.0

executors:
  node:
    docker:
      - image: circleci/node

jobs:
  publish:
    executor: node
    steps:
      - checkout
      - compare-url/reconstruct
      - compare-url/use:
          custom-logic: |
            for FOLDER in packages/*/; do

              package_name=$(basename $FOLDER)

              if [[ $(git diff $COMMIT_RANGE --name-status | grep "$package_name") ]]; then

                echo "changes detected in ${package_name}"

              else
                echo "${package_name} not modified;"
              fi
            done
          step-name: Publish modified orbs

version: 2.1
workflows:
  version: 2
  publish-orbs:
    jobs:
      - publish
