version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  cra:
    type: boolean
    default: false
  nest:
    type: boolean
    default: false
  shared:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

  build:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>

    steps:
      - checkout:
          path: ~/project
      # This step is added only to show that we are in the package directory
      - run:
          name: Content
          command: |
            cat README.md
            echo "<< parameters.package_name >> built." > build.txt
      - run:
          name: Build
          command: echo "Build << parameters.package_name >> ..."
      - persist_to_workspace:
          root: ~/project
          paths:
            - packages/<< parameters.package_name >>

  deploy:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>

    steps:
      - attach_workspace:
          at: ~/project
      # This step is added to show that files are available from the build job.
      - run:
          name: Content to deploy
          command: ls && cat build.txt
      - deploy:
          name: Deploy
          command: echo "Deploying << parameters.package_name >> ..."

workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  # Workflows defined for each package.

  cra:
    when: << pipeline.parameters.cra >>
    jobs:
      - build:
          name: cra-build
          package_name: cra
      - deploy:
          name: cra-deploy
          package_name: cra
          requires:
            - cra-build

  nest:
    when: << pipeline.parameters.nest >>
    jobs:
      - build:
          name: nest-build
          package_name: nest
      - deploy:
          name: nest-deploy
          package_name: nest
          requires:
            - nest-build

  shared:
    when: << pipeline.parameters.shared >>
    jobs:
      - build:
          name: shared-build
          package_name: shared
      - deploy:
          name: shared-deploy
          package_name: shared
          requires:
            - shared-build
